multiple variables

diff --git a/.github/workflows/var_repository.yml b/.github/workflows/var_repository.yml
--- a/.github/workflows/var_repository.yml
+++ b/.github/workflows/var_repository.yml
@@ -46,6 +46,20 @@ jobs:
           OWNER: ${{ needs.Get-Repositories-To-Inject.outputs.OWNER }}
           ENV-NAME: ${{ needs.Get-Repositories-To-Inject.outputs.ENV-NAME }}
         run: |
+            echo "${{ env.OWNER }}"
+            echo "${{ matrix.repositorie }}"
+            
+            response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${{ env.GH_TOKEN }}" "https://api.github.com/repos/${{ env.OWNER }}/${{ matrix.repositorie }}")
+
+            # Verificar el código de respuesta
+            if [ "$response" -eq 200 ]; then
+              echo "El repositorio ${{ env.OWNER }}/${{ matrix.repositorie }} existe."
+            else
+              echo "Error: El repositorio ${{ env.OWNER }}/${{ matrix.repositorie }} no existe."
+              exit 1  # Salir con un código de error
+            fi
+
+
             curl -L \
             -X POST \
             -H "Accept: application/vnd.github+json" \
